# NumPy
Numpy is a general-purpose aray-processing package. It provide a high peformance multidimensional array objectm and tools for working with these array. It is the fundamental package for scientific computing with python.

## What is an array
An array is a data stucture that stores value of the same data type. In python, this is the main difference between the arrays and the list. While list can contian the different type of values corresponding to different data types, array in python can only containd element of same data types.

### To install numpy
pip install numpy : for manual python
conda install numpy : for conda prompt

In [2]:
# initially lest import numpy
import numpy as np

In [2]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)

In [3]:
print(type(my_list))
type(arr)

<class 'list'>


numpy.ndarray

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
print(my_list)

[1, 2, 3, 4, 5]


In [6]:
arr

array([1, 2, 3, 4, 5])

it is the one dimensional array

## arr.shape
This function give the shape of an array

In [7]:
arr.shape

(5,)

this is how 1D array is represent

## 2D array

In [8]:
l1=[1,2,3,4,5]
l2=[6,7,8,9,1]
l3=[2,3,4,5,6]
l4=[7,8,9,1,2]

arr=np.array([l1,l2,l3,l4])

In [9]:
print(arr)

[[1 2 3 4 5]
 [6 7 8 9 1]
 [2 3 4 5 6]
 [7 8 9 1 2]]


In [10]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [2, 3, 4, 5, 6],
       [7, 8, 9, 1, 2]])

In [11]:
arr.shape

(4, 5)

## reshape(p1,p2)
this function is use tho reshape the array

In [12]:
arr.reshape(5,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 9, 1, 2]])

In [13]:
arr.reshape(2,10)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 1],
       [2, 3, 4, 5, 6, 7, 8, 9, 1, 2]])

### Indexing
#### arr[index] : for 1D

In [14]:
# access the array element
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr[8]

9

#### For 2D

In [15]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

arr[row,column]

In [16]:
arr=np.array([l1,l2,l3,l4])
arr[3,1]

8

arr[ : , : ]

colons(:) means it will pick all the rows and column

In [17]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [2, 3, 4, 5, 6],
       [7, 8, 9, 1, 2]])

arr[a:b, : ]
form a row to b row all element


In [18]:
# pick all element form first two rows
arr[0:2,:]

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1]])

### Pick three elements form first two rows
arr[0:2,0:3]


In [19]:
arr[0:2,0:3]
#arr[from 0th row : till 1st row , for 0th column : till 2nd column]

array([[1, 2, 3],
       [6, 7, 8]])

In [20]:
## pick last 2*2 matix for arr
arr[2:4,3:5]
#arr[from 2th row : till 3st row , for 3th column : till 5nd column]

array([[5, 6],
       [1, 2]])

# Some inbuilt function in numpy
## 1. arange([ start, ] stop [ ,step , ] ,dtype=None)

In [21]:
arr=np.arange(0,10)
# it will create an array range form 0 to 10

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr=np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

## 2. np.linspace(start,stop,num=50)

here num=50 means that between stat and stop range we need 50 elements

to get the detail of a function : Place the cursor inside the parenthesis of the function, hold down shift , and press tab .

In [24]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

## 3.copy() function and broadcasting


In [25]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

# replace all element after 3rd index with 100
arr[3:]=100
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100, 100])

In [26]:
arr1=arr

In [27]:
arr1[3:]=500

In [28]:
arr1

array([  1,   2,   3, 500, 500, 500, 500, 500, 500, 500])

In [29]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500, 500])

array is a reference type therefore they are sharing a same memory therefor if we will see the reflection on other array if we make changes if one array .
So, to avoid this we use the copy() function where it will create anothe memory space 

In [30]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr1=arr.copy()
arr[3:]=100
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100, 100])

In [31]:
arr1[3:]=500
arr1

array([  1,   2,   3, 500, 500, 500, 500, 500, 500, 500])

In [32]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100, 100])

## Some condition very useful in exploration data analytics

In [33]:
val=2
arr<2


array([ True, False, False, False, False, False, False, False, False,
       False])

In [34]:
# multiple by 2
arr*2

array([  2,   4,   6, 200, 200, 200, 200, 200, 200, 200])

In [37]:
# need exectly element less the 2
arr[arr<2]

array([1])

In [ ]:
# create array and reshape
np.arange(0,10).reshape(5,2)

## np.ones()

In [ ]:
np.ones(4)


it is haveig dot because default value is float of this function so we have to change dtype parameter in this function to get another datatype value

In [ ]:
np.ones(4,dtype=int
       )

In [ ]:
np.ones((2,5),dtype=int)

## random.rand()
give random value between 0 and 1

In [ ]:
# random distribution
np.random.rand(3,3)

## random.randn()

In [ ]:
arr_ex=np.random.randn(4,4)
arr_ex

In [ ]:
np.random.randint(0,100,8).reshape(2,4)

# some other examples


In [39]:
a = np.array([[1 , 2, 3, 4], [5, 0, 7, 8], [9, 10, 11, 12]])
print(a[a<5])

[1 2 3 4 0]


In [40]:
five_up=(a>5)
print(a[five_up])

[ 7  8  9 10 11 12]


In [41]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  0  8 10 12]


In [42]:
c = a[(a > 2) & (a < 11)]
>>> print(c)

[ 3  4  5  7  8  9 10]


In [43]:
five_up = (a > 5) | (a == 5)
>>> print(five_up)

[[False False False False]
 [ True False  True  True]
 [ True  True  True  True]]


## np.nonzeroe()
 np.nonzero() to print the indices of elements that are, for example, less than 5:

In [14]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b=np.nonzero(a<5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In this example, a tuple of arrays was returned: one for each dimension. The first array represents the row indices where these values are found, and the second array represents the column indices where the values are found.

If you want to generate a list of coordinates where the elements exist, you can zip the arrays, iterate over the list of coordinates, and print them. For example:

In [15]:
>>> list_of_coordinates= list(zip(b[0], b[1]))

>>> for coord in list_of_coordinates:
...     print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


## np.concatenate()
 You can concatenate them with np.concatenate().

In [5]:

>>> x = np.array([[1, 2], [3, 4]])
>>> y = np.array([[5, 6]])
>>> np.concatenate((x, y), axis=0)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
# z = np.concatenate((x, y), axis=0)
# z1 = z[np.newaxis, :]
# print(z.shape)
# print(z1.shape)
# q=np.array([[2,3]])
# np.concatenate((z,q), axis = )

# know the shape and size of an array
### ndarray.ndim
will tell you the number of axes, or dimensions, of the array.

### ndarray.size
will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

### ndarray.shape 
will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

## Slicing

In [12]:
data = np.array([1, 2, 3])
data[-2:]

array([2, 3])

In [13]:
data[:-1]

array([1, 2])

## min max 

In [16]:
>>> a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
...               [0.54627315, 0.05093587, 0.40067661, 0.55645993],
...               [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [17]:
a.sum()

4.8595784

In [18]:
a.min()

0.05093587

In [20]:
a.max()

0.82485143

In [22]:
# from a particular axis
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [23]:
a.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

## np.unique()

In [25]:
>>> a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [26]:
# print the index of a unique a value
>>> unique_values, indices_list = np.unique(a, return_index=True)
>>> print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


## arr.transpose()
this function transpose the matrix
## Reverse the array: np.flip()


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [30]:
>>> arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
>>> reversed_arr = np.flip(arr_2d)
>>> print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


### reverse only rows


In [31]:
>>> reversed_arr_rows = np.flip(arr_2d, axis=0)
>>> print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


### reverse only column

In [32]:
>>> reversed_arr_rows = np.flip(arr_2d, axis=1)
>>> print(reversed_arr_rows)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


## Conert multidimensional array into 1D array : arr.flatten()


In [36]:
>>> x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x2=x.flatten()
print(x2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


if we use flatten() function then any changes in x1 will not effect on x 
but insted if we use ravel() function the any change in x1 will effect to x