# Pandas 
Panda is an open souce, BSD-licenced liberary provideing high-performance, easy to use data strutue and data analysis tools for the python programmming language.

## agenda 
1. What is Data Frame?
2. What is Data Series?
3. Different operation in Pandas

In [1]:
# first step is to import pandas
import pandas as pd
import numpy as np

### pd.DataFrame()
Creating data frame
Init signature: pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)


In [2]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=["Column1","Column2","Column3","Column4"])

In [3]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

### Conver to csv file
dataframe.to_csv("xyz.csv)

In [ ]:
df.to_csv("Test1.csv")

# Accessing the element
## 1 .loc    
syntax: df.iloc[x]

where, x is the name of row or column

loc gets rows (or columns) with particular labels from the index.

eg: df.loc['Row1']
## 2 .iloc
syntax: df.iloc[:,:]

iloc gets rows (or columns) at particular positions in the index (so it only takes integers)
eg: df.iloc[1]

In [6]:

df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int32

In [7]:
type(df.loc["Row1"])

pandas.core.series.Series

In [9]:
df.iloc[1]

Column1    4
Column2    5
Column3    6
Column4    7
Name: Row2, dtype: int32

In [11]:
# taking two rows and 2 cloumns 
df.iloc[0:2,0:2]

Column1  Column2
Row1        0        1
Row2        4        5

In [12]:
type(df.iloc[0:2,0:2])

pandas.core.frame.DataFrame

## df.iloc[:,:].values
### Convert dataFrame into an array i.e. it will skip row and column indexes and just give values.


In [14]:
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [15]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [19]:
df.iloc[:,:].values.shape

(5, 4)

In [20]:
df.iloc[:,:].values.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [40]:
# other then loc or iloc we can call directly by name also
df['Column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int32

In [43]:
# for colling more then one column we have to create a list 
# df['Column3','Column4'] this will give you an error
df[['Column3','Column4']]

Column3  Column4
Row1        2        3
Row2        6        7
Row3       10       11
Row4       14       15
Row5       18       19

### How to check  the null conditions

In [28]:
df.isnull()

Column1  Column2  Column3  Column4
Row1    False    False    False    False
Row2    False    False    False    False
Row3    False    False    False    False
Row4    False    False    False    False
Row5    False    False    False    False

In [29]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [30]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

### Checking how many unique value we have


In [35]:
'''
Below shows that 
12 is present 1 time
4 is present 1 time 
and so on
'''
df["Column1"].value_counts()


12    1
4     1
16    1
8     1
0     1
Name: Column1, dtype: int64

In [38]:
# thake all unique values from cloumn1
df["Column1"].unique()


array([ 0,  4,  8, 12, 16], dtype=int64)